__Pandas Tutorial__

Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structure and data analysis tools for the Python programming language. Pandas helps you work with structured data (like tables or spreadsheets) easily and efficiently.

__Key features__

Data structures:

Series → a one-dimensional labeled array (like a column)

DataFrame → a two-dimensional table (like an Excel sheet)

Data cleaning: handle missing values, filter rows, rename columns

Data analysis: group data, calculate statistics, summarize datasets

File handling: read/write data from CSV, Excel, SQL, JSON, etc.

Time series support: work with dates and time-based data

__Agenda__ 

• What is Data Frames? = Combination of more than one rows and columns

• What is Data Series? = It can either be one row or column

• Different operation in Pandas

In [1]:
# First step is to import pandas

import pandas as pd 
import numpy as np

In [2]:
# Playing with DataFrame and creating one

df = pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns = ['Column1', 'Column2', 'Column3', 'Column4'])

In [3]:
# df.head() shows the first 5 rows of your DataFrame.

df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:
# Creates a new File

df.to_csv('Test1')

In [5]:
# Accessing the elements 
# 1. .loc (just focusing on row indexs)
# 2. .iloc (focuses on both rows and columns indexs)

df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [6]:
# Check the type

type(df.loc['Row1'])

pandas.Series

In [7]:
df.iloc[:,:]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
# For just getting 2 rows

df.iloc[:2]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [9]:
# For 2 rows and 2 columns

df.iloc[:2,:2]

      Column1  Column2
Row1        0        1
Row2        4        5

In [10]:
# Check the type

type(df.iloc[:2,:2])

pandas.DataFrame

In [11]:
print(df.iloc[:2,:1])
print(type(df.iloc[:2,:1]))

      Column1
Row1        0
Row2        4
<class 'pandas.DataFrame'>

In [12]:
df.iloc[0:2,0]

Row1    0
Row2    4
Name: Column1, dtype: int64

In [13]:
type(df.iloc[0:2,0])

pandas.Series

In [14]:
# Take the elements from column 2

df.iloc[:,1:]

      Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [15]:
# Convert Dataframes into Array

df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [16]:
df.iloc[:,1:].values.shape

(5, 3)

In [17]:
# Null Function

df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [18]:
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

__Some inbuilt functions__

In [19]:
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [20]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [21]:
df[['Column3' , 'Column2']]

      Column3  Column2
Row1        2        1
Row2        6        5
Row3       10        9
Row4       14       13
Row5       18       17

__TUT6__

CSV (Comma Separated Values)

In [22]:
# If instead of (,) there is another symbol like (;) that seperates 2 values then add ('Test1.csv', sep = ';')

test_df = pd.read_csv('Test1')

In [23]:
test_df.head()

  Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

In [24]:
df = pd.read_csv('Mercedesbenz.csv')

df refers to entire DataFrame whereas df.head() refers to only the first 5 rows of the DataFrame

In [25]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

__Inbuilt Functions__

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [27]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [28]:
# Get the uniques category counts

df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
as     10
r      10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [29]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [30]:
df['X11'].value_counts()

X11
0    4209
Name: count, dtype: int64

In [31]:
import numpy as np

In [32]:
list_data = [[1,2,3],[3,4,np.nan],[5,6,np.nan],[np.nan,np.nan,np.nan]]

In [33]:
df = pd.DataFrame(list_data)

In [34]:
df.head()

     0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN
2  5.0  6.0  NaN
3  NaN  NaN  NaN

__CSV__

In [35]:
# StringIO converts a string into a file-like object so libraries (like pandas) can read it as if it were a file.
# Whereas BytesIO → works with binary data (bytes)

from io import StringIO, BytesIO

__In Pandas, a space is treated as a real character, not ignored__

In [36]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [37]:
type(data)

str

In [38]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [39]:
# Read from specific columns

df = pd.read_csv(StringIO(data), usecols = ['col1','col3'])

In [40]:
df

  col1  col3
0    x     1
1    a     2
2    c     3

In [41]:
df.to_csv('Test1')

In [42]:
# Specifying columns data types

data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [43]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [44]:
df = pd.read_csv(StringIO(data),dtype=object)

In [45]:
df

   a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [46]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [47]:
df['a'][1]

'5'

In [48]:
df = pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':'Int64'})

In [49]:
df

   a   b     c    d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN

In [50]:
type(df['a'])

pandas.Series

In [51]:
# After df first command is for column then it's for row, and if you want to find using the object(number) use .iloc

print(type(df['a'][1]))
type(df['c'][0])

<class 'numpy.int64'>

numpy.float64

In [52]:
df.dtypes

a      Int64
b      int64
c    float64
d    float64
dtype: object

In [53]:
data3 = ('index,a,b,c\n'
            '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [54]:
# Making 0th index a first column

pd.read_csv(StringIO(data3))

   index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [55]:
# Making 1th index a first column

pd.read_csv(StringIO(data3),index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [56]:
pd.read_csv(StringIO(data3),index_col=2)

     index       a     c
b
bat      4   apple   5.7
cow      8  orange  10.0

In [57]:
data4 = ('a,b,c\n'
        '4,apple,bat\n'
        '8,orange,cow')

In [58]:
pd.read_csv(StringIO(data4))

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [59]:
pd.read_csv(StringIO(data4),index_col = False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [60]:
# Combining usecols and index_col

pd.read_csv(StringIO(data4), usecols=['b', 'c'], index_col = False)

        b    c
0   apple  bat
1  orange  cow

In [61]:
# Quoting and Escape Characters. Very useful in NLP

data6 = 'a,b\n"hello, \\"Bob\\", nice to meet you",5'

In [62]:
pd.read_csv(StringIO(data6),escapechar='\\')

                                a  b
0  hello, "Bob", nice to meet you  5

In [63]:
# URL to CSv

df = pd.read_csv('/Users/manojkumar/Desktop/AI Study/Python/cu.item',sep='\t')

In [64]:
df.head()

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359